exec:
  transaction_time: 1421452800
  transaction_timezone: UTC
in:
  type: file
  paths:
    - examples/csv/
  #parser:
  #  type: csv
  #  newline: LF
  #  columns:
  #    - {name: date_code, type: string}
  #    - {name: customer_code, type: long}
  #    - {name: product_code, type: string}
  #    - {name: employee_code, type: string}
  #  file_decoders:
  #    - type: gzip
out:
  type: file
  directory: tmp/
  file_name: output
  file_ext: csv
  #encoders:
  #  - type: gzip
  #    level: 9
  formatter:
    type: csv
    timezone: Etc/UTC
#in:
#  type: file
#  paths:
#    - benchmark/
#out:
#  type: "null"
